### ISSUE TITLE
Avis d'imposition superfétatoire

### ISSUE THREAD

**Issue by etiennebonnafoux** [MTES-MCT/dossierfacile-backend#298]
Bonjour,

Selon la loi française, l'avis d'imposition fait parti des pièces attestant de ressources et ne peut pas être demandé en plus des bulletins de salaires ( https://www.legifrance.gouv.fr/loda/id/JORFTEXT000031444493 ). 
Cependant Dossier Facile le demande obligatoirement ce qui est une violation de la loi française (ironique pour un site gouvernemental). Si Dossier facile était une personne physique elle aurait 3000 euros d'amende, 15000 euros pour une agence de location.
J'ai essayer de faire remonter le problème par messagerie mais je tombe sur un robot pas des plus intelligent, sans possibilité d'avoir un vrai humain au bout.

Je vous remercie d'avance de l'attention que vous porterai à ma requête.

**Comment by mattboll** [comment]
Bonjour,
La liste des pièces pouvant être exigées par le bailleur contient «Un ou plusieurs documents attestant des ressources» Nous avons choisi de demander l'avis d'imposition de façon pragmatique, car c'est demandé dans la majorité des cas par les bailleurs.
À noter que le robot dont vous parlez correspond à la recherche dans la documentation, il y a également un onglet "Demander" dans l'aide pour parler à un humain. Vous pouvez également envoyer un mail à [contact@dossierfacile.fr](mailto:contact@dossierfacile.fr)

**Comment by etiennebonnafoux** [comment]
Bonjour,

Je vous remercie de votre réponse. Effectivement«Un ou plusieurs documents attestant des ressources» peut être demander. Je pense néanmoins que cette étape ne devrait pas être obligatoire mais seulement conseillé. De mon expérience personnel (je ne sais pas si vous avez des sondages sur les pièces demandés par les bailleurs), l'avis d'imposition du garant n'est pas systématiquement demandé.

Par ailleurs je vous conseillerais d'ajuster votre robot en le faisant signer "réponse automatique" plutôt que "L'équipe DossierFacile" qui trompe sur sa nature et de rajouter un message "Si ce message ne répond pas à votre question, vous pouvez également envoyer un mail à contact@dossierfacile.fr".

En vous remerciant l'attention que vous me portez.

**Comment by mattboll** [comment]
C'est bien noté, J'ai fait remonter le message aux personnes qui s'en occupent
