### ISSUE TITLE
Impossible d'inviter un compte existant en tant que colocataire

### ISSUE THREAD

**Issue by arthaud-proust** [MTES-MCT/dossierfacile-backend#712]
Merci beaucoup pour ce site très utile, merci également qu'il soit en open-source !
Voici une discussion/rapport de bug car je ne sais pas si ce comportement est attendu ou problématique.
[update] : je viens de lire ici que c'était un comportement attendu : https://docs.dossierfacile.logement.gouv.fr/article/7-ajout-dun-colocataire

# Description
Il est impossible d'inviter un compte existant en tant que colocataire, on peut seulement inviter un email qui n'a pas de compte

# Reproduction 
## Arrange
Avoir deux comptes, ici pour l'exemple :
- Compte A : a@email.com
- Compte B : b@email.com

## Act
Avec le compte A:
- se connecter sur dossierFacile.fr
- créer un dossier en colocation
- ajouter l'adresse email du compte B
- cliquer sur continuer 

## Assert
- observer l'erreur "email déjà utilisée"

# Questions :
- est-ce que ce comportement est attendu ? Oui : https://docs.dossierfacile.logement.gouv.fr/article/7-ajout-dun-colocataire
- si oui, quelle est la raison ? Est-elle technique ? 

# Remarque
D'un avis extérieur, pouvoir utiliser une email déjà existante serait pratique. 
En l'état, il faut créer un nouveau compte avec un nouvel email à chaque dossier de colocation.

**Comment by mattboll** [comment]
Bonjour,
merci pour la remontée qui est complète et exhaustive :)
C'est un comportement effectivement attendu et connu, c'est un développement à faire mais le besoin est assez rare et il n'est pas prioritaire pour le moment. Vous pouvez nous contacter sur contact@dossierfacile.fr ou par le chat du site, dans certains cas nous pouvons faire la liaison de notre côté.

Cordialement,

**Comment by arthaud-proust** [comment]
Ok, effectivement s'il y a peu de demandes !J'ai fait tel qu'indiqué avec un nouveau compte, 

merci pour votre réponse
